version: '3'

services:
  wjx_webhook:
    image: registry-vpc.cn-zhangjiakou.aliyuncs.com/xiaoduoai/growth:v1.0.8
    restart: always
    container_name: wjx_webhook
    ports:
      - "9676:9676"
    environment:
      LANG: "en_US.UTF-8"
    volumes:
      - /opt/wjx_webhook:/root/projects/xiaoduo/xiaoduo-mp/wjx_webhook
      - /etc/localtime:/etc/localtime
      - /var/log/xiaoduo:/var/log/xiaoduo
      - /etc/hosts:/etc/hosts
    working_dir: /root/projects/xiaoduo/xiaoduo-mp/wjx_webhook/src
    command:
      - '/usr/local/python3/bin/python3'
      - '-u'
      - 'app.py'
      - '--numprocs=4'
      - '-c'
      - '../config/wjx_webhook.config'