version: '3'

services:
  apisix_admin_py:
    image: registry-vpc.cn-zhangjiakou.aliyuncs.com/xiaoduoai/growth:v1.0.8
    restart: always
    container_name: apisix_admin_py
    ports:
      - "9913:9913"
    networks:
      - net
    environment:
      LANG: "en_US.UTF-8"
    volumes:
      - /opt/apisix-admin-py:/root/projects/xiaoduo/xiaoduo-mp/apisix-admin-py
      - /etc/localtime:/etc/localtime
      - /var/log/xiaoduo:/var/log/xiaoduo
      - /etc/hosts:/etc/hosts
    working_dir: /root/projects/xiaoduo/xiaoduo-mp/apisix-admin-py/src
    command:
      - '/usr/local/python3/bin/python3'
      - '-u'
      - 'app.py'
      - '--numprocs=4'
      - '-c'
      - '../config/apisix-admin-py.conf'

networks:
    net:
        external: false